config/routes.rb
Rails.application.routes.draw do
  mount ShopifyApp::Engine, at: '/'

  get 'modal' => "home#modal", :as => :modal
  get 'modal_buttons' => "home#modal_buttons", :as => :modal_buttons
  get 'regular_app_page' => "home#regular_app_page"
  get 'help' => "home#help"
  get 'pagination' => "home#pagination"
  get 'breadcrumbs' => "home#breadcrumbs"
  get 'buttons' => "home#buttons"
  get 'form_page' => "home#form_page"
  post 'form_page' => "home#form_page"
  get 'error' => 'home#error'

  root :to => 'home#index'
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::Shop
  include ShopifyApp::SessionStorage
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ShopifyApp::AuthenticatedController
  def index
  end

  def modal
  end

  def modal_buttons
  end

  def regular_app_page
  end

  def buttons
  end

  def help
  end

  def error
    raise "An error page"
  end

  def form_page
    if request.post?
      if params[:name].present?
        flash[:notice] = "Created #{ params[:colour] } unicorn: #{ params[:name] }."
      else
        flash[:error] = "Name must be set."
      end
    end
  end

  def pagination
    @total_pages = 3
    @page = (params[:page].presence || 1).to_i
    @previous_page = "/pagination?page=#{ @page - 1 }" if @page > 1
    @next_page = "/pagination?page=#{ @page + 1 }" if @page < @total_pages
  end

end

app/views/home/breadcrumbs.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: 'Breadcrumbs',
        breadcrumb: {
          label: "Regular Page",
          href: "/regular_app_page",
          target: 'app'
        },
        icon: '/shopify.png',
        buttons: {
          secondary: {
            label: "Back",
            href: "/",
            target: 'app'
          }
        }
      });
    });
  </script>
<% end %>

<h1>Breadcrumbs</h1>

<p>In addition to the page title, a single middle level of breadcrumbs can be inserted between the root of the app and the current page. It is defined the same way as a button with label, href, target, loading, etc..</p>

<p>If there is no title set the breadcrumb will not appear.</p>

app/views/home/buttons.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    window.mainPageTitle = 'Buttons Page';

    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: window.mainPageTitle,
        buttons: {
          primary: {label: "Primary", loading: false, callback: function(){ alert('Primary clicked'); } },
          secondary: [
            {label: "Normal", loading: false, callback: function(){ alert('Normal clicked'); } },
            {label: "Danger", loading: false, style: 'danger', callback: function(){ alert('Danger clicked'); } },
            {label: "Disabled", loading: false, style: 'disabled', callback: function(){ alert('Disabled clicked'); } }
          ]
        }
      });
    });
  </script>
<% end %>

<p>
  Buttons can be styled as "danger", "disabled", "primary", or null/undefined as default.
</p>

app/views/home/form_page.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
     window.mainPageTitle = 'Form page';

    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: window.mainPageTitle,
        icon: '/shopify.png',
        buttons: {
          primary: {
            label: "Create Unicorn",
            message: 'save-unicorn-form-message'
          },
          secondary: {
            label: "Back",
            href: "/",
            target: 'app'
          }
        }
      });

    <% if flash[:notice] %>
      ShopifyApp.flashNotice("<%= flash[:notice] %>");
    <% end %>

    <% if flash[:error] %>
      ShopifyApp.flashError("<%= flash[:error] %>");
    <% end %>

    });
  </script>
<% end %>

<h1>Create new Unicorn</h1>

<p>A normal form submitted by a data tag and a button in Shopify. Embedded apps can mostly work exactly like a normal app, except with Shopify admin UI integration.</p>

<form method="POST" action="form_page" data-shopify-app-submit="save-unicorn-form-message">
  <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
  <p>
    <label>Name:</label>
    <input type="text" name="name"/>
  </p>

  <p>
    <label>Colour:</label>
    <select name="colour">
      <option>Pink</option>
      <option>Rainbow</option>
      <option>Purple</option>
    </select>
  </p>

</form>

app/views/home/help.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
     window.mainPageTitle = 'Help Page';

    ShopifyApp.ready(function(){
      ShopifyApp.Bar.setTitle(window.mainPageTitle);
      ShopifyApp.Bar.loadingOff();
    });
  </script>
<% end %>

<h2>Hey! This is the help page.</h2>

<p>You can go back to the previous page clicking on the breadcrumb link on the top bar. =)</p>

app/views/home/index.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    window.mainPageTitle = 'Main Page';
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: window.mainPageTitle,
        icon: '/shopify.png',
        buttons: {
          secondary: {
            label: "Documentation",
            href: "http://docs.shopify.com/embedded-app-sdk",
            target: 'new'
          }
        }
      });
    });
  </script>
<% end %>

<h2>Shopify Embedded Example.</h2>

<p>This application demos the various ways an app can now interact with the Shopify Admin. See the project README for details.</p>

<p><a href="regular_app_page">Links to another page</a> work normally.</p>

<h2>Function calls</h2>
<ul>
  <li><a href="#" onclick="ShopifyApp.Bar.loadingOff()">Turn spinner off</a></li>
  <li><a href="#" onclick="ShopifyApp.Bar.loadingOn()">Turn spinner on</a></li>
  <li><a href="#" onclick="window.mainPageTitle = window.mainPageTitle + '!'; ShopifyApp.Bar.setTitle(window.mainPageTitle)">Add an exclamation mark to the title</a></li>
  <li><a href="#" onclick="ShopifyApp.redirect('/orders')">Redirect to /orders within the Shopify Admin</a></li>

  <li><a href="#" onclick="ShopifyApp.flashNotice('Flash a notice message.');">Flash notice</a></li>
  <li><a href="#" onclick="ShopifyApp.flashError('Flash an error message.');">Flash error</a></li>
  <li><a href="#" onclick="ShopifyApp.Bar.setPagination({previous: {loading: false, callback: function(){alert('Previous clicked'); } }}); return false">Add pagination buttons</a></li>
</ul>


<!--
  This is example code, focusing on simplicity.
  Try not to use 'onclick' attributes in real applications. Use unobtrusive JavaScript instead.
  http://en.wikipedia.org/wiki/Unobtrusive_JavaScript)

  See modals.js for the implementation of these calls.
-->

<h2>Modal Windows</h2>
<ul>
  <li><a href="#" onclick="alertModal()">Alert modal</a></li>
  <li><a href="#" onclick="confirmModal()">Confirm modal</a></li>
  <li><a href="#" onclick="inputModal('Enter a value:')">Prompt modal</a></li>
  <li><a href="#" onclick="newModal('<%= modal_url %>','This is a custom modal title')">Modal window containing an iframe</a></li>
  <li><a href="#" onclick="newButtonModal('<%= modal_buttons_url %>','This modal has many buttons')">Modal window with a variety of buttons</a></li>
</ul>

<h2>Integrations</h2>
<ul>
  <li><a href="form_page">Go to form page</a></li>
  <li><a href="pagination">Pagination links</a></li>
  <li><a href="breadcrumbs">Breadcrumbs</a></li>
  <li><a href="buttons">Buttons</a></li>
</ul>

<h2>Error pages</h2>
<ul>
  <li><a href="/404.html">Error 404</a></li>
  <li><a href="/500.html">Error 500</a></li>
</ul>

app/views/home/modal.html.erb
<h2>This content is displayed on a modal window!</h2>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tollenda est atque extrahenda radicitus. Animum autem reliquis rebus ita perfecit, ut corpus; Duo Reges: constructio interrete. Dat enim intervalla et relaxat. Igitur neque stultorum quisquam beatus neque sapientium non beatus. Est autem etiam actio quaedam corporis, quae motus et status naturae congruentis tenet; 
Quam illa ardentis amores excitaret sui! Cur tandem? Nos commodius agimus. Nihil minus, contraque illa hereditate dives ob eamque rem laetus. Quis enim est, qui non videat haec esse in natura rerum tria? Qui non moveatur et offensione turpitudinis et comprobatione honestatis? Summus dolor plures dies manere non potest? Cum autem in quo sapienter dicimus, id a primo rectissime dicitur. Levatio igitur vitiorum magna fit in iis, qui habent ad virtutem progressionis aliquantum. At ego quem huic anteponam non audeo dicere; Sed venio ad inconstantiae crimen, ne saepius dicas me aberrare; 
Quid enim de amicitia statueris utilitatis causa expetenda vides. Quodcumque in mentem incideret, et quodcumque tamquam occurreret. Age nunc isti doceant, vel tu potius quis enim ista melius? Cum id fugiunt, re eadem defendunt, quae Peripatetici, verba. Beatus autem esse in maximarum rerum timore nemo potest. Non dolere, inquam, istud quam vim habeat postea videro; Omnia contraria, quos etiam insanos esse vultis. Duo enim genera quae erant, fecit tria. Ergo, si semel tristior effectus est, hilara vita amissa est? 
Videmusne ut pueri ne verberibus quidem a contemplandis rebus perquirendisque deterreantur? Paria sunt igitur. At ego quem huic anteponam non audeo dicere; Ex eorum enim scriptis et institutis cum omnis doctrina liberalis, omnis historia. Mene ergo et Triarium dignos existimas, apud quos turpiter loquare? Ut non sine causa ex iis memoriae ducta sit disciplina. Qui non moveatur et offensione turpitudinis et comprobatione honestatis? Quid ergo aliud intellegetur nisi uti ne quae pars naturae neglegatur? Hoc est non modo cor non habere, sed ne palatum quidem. </p>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tu quidem reddes; Quis istud possit, inquit, negare? 
Cave putes quicquam esse verius. Cave putes quicquam esse verius. Isto modo ne improbos quidem, si essent boni viri. Non quam nostram quidem, inquit Pomponius iocans; 
Propter nos enim illam, non propter eam nosmet ipsos diligimus. Non igitur de improbo, sed de callido improbo quaerimus, qualis Q. Ut optime, secundum naturam affectum esse possit. Duo Reges: constructio interrete. Quae quidem vel cum periculo est quaerenda vobis; 
Prodest, inquit, mihi eo esse animo. Eaedem res maneant alio modo. Bonum patria: miserum exilium. In his igitur partibus duabus nihil erat, quod Zeno commutare gestiret. </p>  

app/views/home/modal_buttons.html.erb
<h2>This content is content is an iframe.</h2>

<p>
  Modals accept an object of buttons. The object can contain keys as follows:

  <ul>
    <li>`primary`: Max 2 button. Floated right. Defaults to green, and the only button that can be green.</li>
    <li>`secondary`: Max 2 buttons. Floated right after the primary button.</li>
    <li>`tertiary`: Max 2 buttons. Floated left.</li>
  </ul>
</p>

app/views/home/pagination.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    window.mainPageTitle = 'Pagination (<%= @page %> of <%= @total_pages %>)';

    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: window.mainPageTitle,
        icon: '/shopify.png',
        buttons: {
          secondary: {
            label: "Back",
            href: "/",
            target: 'app'
          }
        },
        pagination: {
          previous: <%= (@previous_page.present? ? {href: @previous_page} : nil).to_json.html_safe %>,
          next: <%= (@next_page.present? ? {href: @next_page} : nil).to_json.html_safe %>
        }
      });
    });
  </script>
<% end %>

<h1>Pagination</h1>

<p>Now viewing page <%= @page %> of <%= @total_pages %>.</p>

<p>Pagination links at the top page can load a passed in URL or a Javascript callback.</p>

app/views/home/regular_app_page.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    window.mainPageTitle = 'Regular Page';

    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: window.mainPageTitle,
        buttons: {
          secondary: [
            {
              label: "Documentation",
              href: "http://docs.shopify.com/embedded-app-sdk",
              target: 'new'
            },
            {
              label: "Back",
              href: "/",
              target: 'app'
            }
          ]
        }
      });
    });
  </script>
<% end %>

<h2>Regular application page with different top bar</h2>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Primum in nostrane potestate est, quid meminerimus? Mihi quidem Antiochum, quem audis, satis belle videris attendere. Nummus in Croesi divitiis obscuratur, pars est tamen divitiarum. Earum etiam rerum, quas terra gignit, educatio quaedam et perfectio est non dissimilis animantium. At hoc in eo M. Duo Reges: constructio interrete. Quia nec honesto quic quam honestius nec turpi turpius. Nihilne te delectat umquam -video, quicum loquar-, te igitur, Torquate, ipsum per se nihil delectat? Dicimus aliquem hilare vivere;
Et ille ridens: Video, inquit, quid agas; Esse enim quam vellet iniquus iustus poterat inpune. In his igitur partibus duabus nihil erat, quod Zeno commutare gestiret. Et ille ridens: Video, inquit, quid agas; Quid est, quod ab ea absolvi et perfici debeat? Quid ergo? Quod cum dixissent, ille contra. Ille enim occurrentia nescio quae comminiscebatur; Qua ex cognitione facilior facta est investigatio rerum occultissimarum.
Cur tantas regiones barbarorum pedibus obiit, tot maria transmisit? Superiores tres erant, quae esse possent, quarum est una sola defensa, eaque vehementer. Omnia peccata paria dicitis. Nam quid possumus facere melius?
Mihi vero, inquit, placet agi subtilius et, ut ipse dixisti, pressius. Est enim tanti philosophi tamque nobilis audacter sua decreta defendere. Hinc ceteri particulas arripere conati suam quisque videro voluit afferre sententiam. Qui autem esse poteris, nisi te amor ipse ceperit? Non quam nostram quidem, inquit Pomponius iocans; Hanc quoque iucunditatem, si vis, transfer in animum; </p>

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    var eventName = typeof(Turbolinks) !== 'undefined' ? 'page:change' : 'DOMContentLoaded';

    document.addEventListener(eventName, function() {
      <% if flash[:notice] %>
        ShopifyApp.flashNotice("<%= escape_javascript flash[:notice].html_safe %>");
      <% end %>

      <% if flash[:error] %>
        ShopifyApp.flashError("<%= escape_javascript flash[:error].html_safe %>");
      <% end %>
    });
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Example</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Shopify Embedded Example App</title>
    <%= stylesheet_link_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="app-wrapper">
      <div class="app-content">
        <main role="main">
          <%= yield %>
        </main>
      </div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>

    <script type="text/javascript">
      ShopifyApp.init({
        apiKey: "<%= ShopifyApp.configuration.api_key %>",
        shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
        debug: false,
        forceRedirect: true
      });
    </script>

    <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>